#ifndef ANALIZADORLEXICOPYTHON_GESTION_DE_ERRORES_H
#define ANALIZADORLEXICOPYTHON_GESTION_DE_ERRORES_H

#define ERR_NUMERO_DE_ARGUMENTOS_INCORRECTO 1
#define ERR_FICHERO_NO_ABRE 2
#define ERR_FICHERO_NO_PYTHON 3
#define ERR_CARACTER_NO_RECONOCIDO 4
#define ERR_TAMANO_MAXIMO_DE_LEXEMA_EXCEDIDO 5

void lanzar_error(int codigo_de_error, int fila, int columna);

#endif //ANALIZADORLEXICOPYTHON_GESTION_DE_ERRORES_H
